admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  clusters:
  - name: admin
    connect_timeout: 1s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: admin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              pipe:
                path: /sockets/admin.socket

  - name: cockpit
    connect_timeout: 2s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cockpit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 9090

  listeners:
  # admin listener
  - name: admin
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: admin
          route_config:
            name: admin
            virtual_hosts:
            - name: admin
              domains:
              - "*"
              routes:
              - name: ready
                match:
                  path: /ready
                route:
                  cluster: admin
              - name: metrics
                match:
                  path: /metrics
                route:
                  cluster: admin
                  prefix_rewrite: /stats/prometheus
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  # inbound API requests
  - name: ingress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          stat_prefix: ingress
          route_config:
            name: ingress
            virtual_hosts:
            - name: api_hosts
              domains:
                  - "*"
              routes:
              - match:
                  prefix: /
                route:
                  cluster: cockpit

          http_filters:
          - name: faux_auth
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                faux_auth:
                  issuer: faux_auth
                  forward: false
                  local_jwks:
                    filename: /app/auth/jwks.json
              # todo rules
              rules:
              - match:
                  prefix: /
                requires:
                  provider_name: faux_auth

          # This is mandatory in order to have the HTTP routes above.
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

